name: LevelBorder
main: runi.myddns.levelborder.LevelBorderMain
version: '1.2'
author: Runi
api-version: 26.2

commands:
  lbscore:
    description: Steuert das LevelBorder-Scoreboard.
    usage: /lbscore <reset|reload|hide>

  levelborder:
    description: Hauptbefehl für LevelBorder.
    usage: /levelborder <subcommand>
    aliases: [lb]

  optionen:
    description: Öffnet das LevelBorder Optionen-Menü
    usage: /optionen
    aliases: [ options ]