name: LevelBorder
main: runi.myddns.levelborder.LevelBorderMain
version: '1.1.1'
author: Runi
api-version: 26.1.2

commands:
  lbscore:
    description: Steuert das LevelBorder-Scoreboard.
    usage: /lbscore <reset|reload|hide>

  levelborder:
    description: Hauptbefehl für LevelBorder.
    usage: /levelborder <subcommand>
    aliases: [lb]